### ISSUE TITLE
Feeds not available

### ISSUE THREAD

**Issue by kennymc-c** [ThisIsBenny/Spotify-Podcast-Feed#2]
Since today I can not download or stream any episodes from podcasts added via the vercel.app URL in Overcast. Apple Podcasts App also has this problem. Can anyone confirm this?

**Comment by ThisIsBenny** [comment]
Hi @kennymc-c Spotify have change something and it isn‘t possible to access the auto stream as needed for a podcast player. you will find more details here: https://spotifeed.timdorr.com/

**Comment by ThisIsBenny** [comment]
@kennymc-c should be fixed

**Comment by kennymc-c** [comment]
My existing podcasts seem to be working again now but certain URLs still don't work like
https://spotify-podcast-feed.vercel.app/0PyBsYclXafVAMjUQ6nI2j or
https://spotify-podcast-feed.vercel.app/16trkMhwBWxjkvDG7FMQ7B

One of the working ones is e.g. https://spotify-podcast-feed.vercel.app/1OLcQdw2PFDPG1jo3s0wbp

**Comment by ThisIsBenny** [comment]
looks like there is not a public audio link for every podcast 😔

Without public link:
```
[
  {
    url: 'https://anon-podcast.scdn.co/2924fd3fb3c1fd3a83ba6a745a4130d129c8d4d5',
    format: 'OGG_VORBIS_96',
    fileId: '2924fd3fb3c1fd3a83ba6a745a4130d129c8d4d5',
    externallyHosted: false
  },
  {
    url: 'https://anon-podcast.scdn.co/9aef1297f8be64bab8d69f7e148ac5982c7ee123',
    format: 'MP4_128_DUAL',
    fileId: '9aef1297f8be64bab8d69f7e148ac5982c7ee123',
    externallyHosted: false
  },
  {
    url: 'https://anon-podcast.scdn.co/cbaaf8f6423d2d464cd31dd261cb213bd1f07ad2',
    format: 'AAC_24',
    fileId: 'cbaaf8f6423d2d464cd31dd261cb213bd1f07ad2',
    externallyHosted: false
  },
  {
    url: 'https://anon-podcast.scdn.co/f3a5adadc8409539d8648486157b9a7deb3ac010',
    format: 'MP4_128',
    fileId: 'f3a5adadc8409539d8648486157b9a7deb3ac010',
    externallyHosted: false
  }
]
```

With public link:

```
[
  {
    url: 'https://anon-podcast.scdn.co/02fcc3092d07362fb89899a14efcdf00c4205c13',
    format: 'MP4_128',
    fileId: '02fcc3092d07362fb89899a14efcdf00c4205c13',
    externallyHosted: false
  },
  {
    url: 'https://anon-podcast.scdn.co/c9b6a0f8fce4022a5509ded10685dfab808f15b1',
    format: 'AAC_24',
    fileId: 'c9b6a0f8fce4022a5509ded10685dfab808f15b1',
    externallyHosted: false
  },
  {
    url: 'https://anon-podcast.scdn.co/8e7c7188a24ab7168d80395ca179c7ea8db18b90',
    format: 'MP4_128_DUAL',
    fileId: '8e7c7188a24ab7168d80395ca179c7ea8db18b90',
    externallyHosted: false
  },
  {
    url: 'https://anon-podcast.scdn.co/4fe9c6ee9797ad73f98954e42d7202b285e029d3',
    format: 'OGG_VORBIS_96',
    fileId: '4fe9c6ee9797ad73f98954e42d7202b285e029d3',
    externallyHosted: false
  },
  {
    url: 'https://traffic.megaphone.fm/GLT1570693403.mp3',
    format: 'UNKNOWN',
    fileId: null,
    externallyHosted: true
  }
]
```

I see at the moment no way to support podcasts where `externallyHosted` false 😕

**Comment by kennymc-c** [comment]
Today I noticed again problems with different feeds not loading new episodes. 
Curl shows a feed without episodes for https://spotify-podcast-feed.vercel.app/1OLcQdw2PFDPG1jo3s0wbp. Same result with other shows like https://spotify-podcast-feed.vercel.app/7BTOsF2boKmlYr76BelijW or https://spotify-podcast-feed.vercel.app/1k7OSBc2faoeg9G1Rb92pr.
Is this the same problem? How can I find out myself if the podcast still uses public links?

**Comment by ThisIsBenny** [comment]
@kennymc-c spotify changed the API structure and it looks like that you don't have access anymore to the audio stream as "guest". You have to be logged in to get the URL.

**Comment by kennymc-c** [comment]
Thanks, your recent changes have solved the problem

**Comment by lkstnr** [comment]
There seems to be a way around this: [librespot-python/issues/135](https://github.com/kokarare1212/librespot-python/issues/135) 

Is this applicable for this project?

**Comment by ThisIsBenny** [comment]
Hi @lkstnr, there are mentioning in the mentioned issue the same problem which can't be solved. Spotify doesn't provide anymore an external URL which can be used in an normal podcast app. Even if you are logged in in the Spotify web play, you will not see this type of url.

**Comment by klamann** [comment]
@ThisIsBenny are you sure this is unfixable? It seems to me like librespot-python figured it out, as mentioned in 
[this comment](https://github.com/kokarare1212/librespot-python/issues/135#issuecomment-1171364255):

> The original problem - not being able to download episodes - is now solved, I assume partly due to the inclusion of the `client-token`, partly due to me refactoring _spodcast_ to use _librespot-python_-provided API interfaces instead of raw web API access.

I really enjoy having spotify podcasts in my regular podcatcher, thanks for providing this service :)

**Comment by ThisIsBenny** [comment]
@klamann the two comments after the one you mentioned are telling the same issue. Spotify doesn't provide anymore an external URL which can be used in a normal podcast app. Even when I am logged in (client-token is set), this URL is not available.

You can test it my your own, when you open the spotify web player and checks in the Browser Dev Tools the Response of the https://api-partner.spotify.com/pathfinder/v1/query?operationName=queryPodcastEpisodes Request. In the past, the audio array of each episode includes one object where "externallyHosted" was true and the url was a "megaphone" url. Now, this array includes only none external hosted URLs which are not working in normal podcast apps.
